# Site settings
title: NBW & Co
email: nbwandco@gmail.com
whatsapp: https://wa.me/60146106831
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nbwassociate.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
